site_name: Quant Wiki 中文量化百科
site_url: https://quant-wiki.com
site_author: LLMQuant Team
site_description: A comprehensive quantitative trading and finance wiki

# Repository
repo_name: LLMQuant/quant-wiki
repo_url: https://github.com/LLMQuant/quant-wiki
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2024 LLMQuant Team


# Navigation
nav:
  - 简介: 
    - 关于项目: index.md
    - 如何参与: contribute.md
    - 常见问题: FAQ.md
    - 关于LLMQuant社区: about.md
    - 社区其他项目: other.md
    - 加入我们: join.md
  - 基本概念:
    - 知识框架: basic/framework.md
    - 金融术语: basic/index.md
    - 量化行话: basic/lingo.md
  - 入门教程: 
    - 夏普比率: start/sharpe.md
    - 期权定价: start/option.md
    - 波动率: start/volatility.md
    - 代资产组合理论: start/mpt-markowitz.md
  - 量化前沿:
    - Strategies: advanced/strategies.md
  - 量化策略库:  
    - Overview: strat/overview.md
    - 事件驱动型: strat/event-driven.md
    - 趋势型: strat/trend-following.md
    - 统计套利型: strat/stat-arb.md
    - 九个热门策略: strat/nine-strategies.md
    - Point72策略: strat/point72-idea.md
  - AI+量化:  
    - 使用大语言模型揭露企业年报中掩盖的坏消息: ai/report.md
    - Reference: ai/reference.md
  - 量化图书馆:
    - Overview: library/overview.md
    - Reference: library/reference.md
  - 行业内幕:
    - 量化策略库: industry/overview.md
    - 量化策略库参考: industry/reference.md
  - 求职专区:
    - Overview: api/overview.md
    - Reference: api/reference.md
  - Chatbot:
    - Overview: chatbot/overview.md

extra_css:
  - stylesheets/extra.css
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css

# Configuration
theme:
  name: material
  logo: asset/quant-wiki.svg # logo 图标
  favicon: asset/quant-wiki.svg # 网页标签图标
  icon:
    repo: fontawesome/brands/github
  font:
    text: LXGW WenKai Mono TC
    code: Roboto Mono
  language: zh
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  # https://facelessuser.github.io/pymdown-extensions/extensions/betterem/
  - pymdownx.betterem
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true

# Plugins
plugins:
  - search
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
  # - git-revision-date-localized:
      # type: datetime

# Extra CSS and JavaScript
extra_css:
  - assets/stylesheets/extra.css

extra_javascript:
  - assets/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js



extra:
  social:  # This is the social links section.
    # - icon: fontawesome/brands/github  # Use the Font Awesome icon name.
      # link: https://github.com/your-username  # Replace with your GitHub username.
      # name:  Visit me on GitHub # 用于 accessibility 的名字
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/llmquant/
    - icon: fontawesome/solid/globe
      link: https://llmquant.com