name: Build and Deploy MkDocs

on:
  push:
    branches:
      - main  # 或者你的主分支名称

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build MkDocs
      run: mkdocs build

    - name: Debug SSH
      run: |
        ssh-add -l || echo "No SSH key loaded"
        ssh -vvv -o StrictHostKeyChecking=no -p ${{ secrets.SERVER_PORT || '22' }} \
          ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} exit

    - name: List SSH folder
      run: |
        echo "==> Listing ~/.ssh directory..."
        ls -la ~/.ssh || echo "~/.ssh not found"

    - name: Deploy to server
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -p ${{ secrets.SERVER_PORT || '22' }} ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
        rsync -e 'ssh -p ${{ secrets.SERVER_PORT || '22' }}' -avz --delete /github/workspace/site/ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/www/wwwroot/wiki/